SAMPLE_RATE = 16000
FRAMES_PER_SEC = 100

WINDOW_SIZE = 2048
HOP_SIZE = 160
PAD_MODE = "reflect"
WINDOW = "hann"
CHANNELS_NUM = 1

NOTES_NUM_EXCLUDE_SILENCE = 88
NOTES_NUM = NOTES_NUM_EXCLUDE_SILENCE + 1
BEGIN_NOTE = 21
N_FFT = WINDOW_SIZE
