from conf.feature import *

SOURCES_NUM_OF_MIXTURE = 2
UP_BOUND = 2
SHIFT_SEMITONE = 4
POS_SHIFT_SEMITONE = int( 2 * SHIFT_SEMITONE + 1)
DURATION = 3
SAMPLE_DURATION = int(SAMPLE_RATE * DURATION)
FRAME_DURATION = int(FRAMES_PER_SEC * DURATION)

LEARNING_RATE = 5e-4
DECAY = 100
TRAINING_BATCH_SIZE = 12
SAMPLES_NUM = 6240
